#!/bin/bash
epochs=100000
eta=0.000001
dim=2
tol=0.00000000001
#options for the optimizator
while [[ $# -gt 0 ]]; do
    case "$1" in

    --epochs=*)
        epochs="${1#*=}"
        ;;
    --eta=*)
        eta="${1#*=}"
        ;;
    --tol=*)
        tol="${1#*=}"
        ;;
    --dim=*)
        dim="${1#*=}"
        ;;
    *)
    echo "Unknown argument: '$1'"
        exit 1
        ;;
    esac
    shift
done

python3 SGD.py "$epochs" "$eta" "$dim" "$tol"